FROM node:20-slim

WORKDIR /app

# Copy root package.json for Vite frontend
COPY package*.json ./
RUN npm install

# Copy frontend source code
COPY . .

EXPOSE 5173

# Run Vite dev server, exposed to 0.0.0.0 so it can be accessed outside the container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
